install.packages("readxl")
library(readxl)
data1 <- read_excel("Judicial Extra Income Record 2014.xlsx", sheet=1)
table(data1$`JUDICIAL POSITION`)
data21 <- read_excel("Refined Version.xlsx", sheet=1)
data22 <- read_excel("Refined Version.xlsx", sheet=2)
data23 <- read_excel("Refined Version.xlsx", sheet=3)
data24 <- read_excel("Refined Version.xlsx", sheet=4)
data25 <- read_excel("Refined Version.xlsx", sheet=5)
data26 <- read_excel("Refined Version.xlsx", sheet=6)
data27 <- read_excel("Refined Version.xlsx", sheet=7)

colnames(data22)
colnames(data23)
colnames(data24)
colnames(data25)
colnames(data26)
